trip/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'events#index'

  resources :events do
    scope module: :events do
      resources :attends, only: [:new, :create, :destroy]
      resources :favorites, only: [:create, :destroy]
      resources :details_images, only: [:create, :destroy]
    end
  end

  resources :users, only: [:show, :edit, :update]

  namespace :users do
    resources :mylists, only: [:show]
  end

  post 'search', to: 'search#index'
  get 'search', to: 'search#index'

  resources :places, only: [:index]

  post 'line_callback', to: "line#callback"

end

trip/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :f_name, presence: true
  validates :l_name, presence: true

  mount_uploader :avatar, AvatarUploader

  enum gender: { male: 0, female: 1 }

  has_many :events
  has_many :attends
  has_many :favorites

  def fullname
    return "#{f_name} #{l_name} "
  end

end

trip/app/controllers/users/mylists_controller.rb
class Users::MylistsController < ApplicationController
  before_action :find_user_events, only: [:show]

  def show
    if params[:list_name] == "attended"
      @user_attend_list = @user.attends
      @events = []
      @user_attend_list.each do |attend_event|
        @event = Event.find(attend_event.event_id)
        @events << @event if @event.end_date < Time.now
      end
    elsif params[:list_name] == "apply"
      @user_attend_list = @user.attends
      @events = []
      @user_attend_list.each do |attend_event|
        @event = Event.find(attend_event.event_id)
        @events << @event if @event.start_date > Time.now
      end
    elsif params[:list_name] == "fav"
      @user_fav_list = @user.favorites
      @events = []
      @user_fav_list.each do |fav_event|
        @events << Event.find(fav_event.event_id)
      end
    elsif params[:list_name] == "producer"
      @events = @user.events.order('id DESC')
    end
    @events = Kaminari.paginate_array(@events).page(params[:page])
  end

  private

  def find_user_events
    @user = User.find(params[:id])
  end
end

trip/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:show,:edit,:update]

  def show
    find_user
    @user_attend_list = @user.attends
    @events = []
    @user_attend_list.each do |attend_event|
      @event = Event.find(attend_event.event_id)
      @events << @event if @event.end_date < Time.now
    end
    @events = Kaminari.paginate_array(@events).page(params[:page])
  end

  def edit
    find_user
  end

  def update
    find_user
    if params[:user][:password] == ""
      @user.update(update_params)
      if @user.errors.present?
        flash[:error] = @user.errors.full_messages
        redirect_to :back and return
      end
    else
      @user.update(update_params_with_password)
      if @user.errors.present?
        flash[:error] = @user.errors.full_messages
        redirect_to :back and return
      end
      redirect_to '/users/sign_in' and return
    end
    redirect_to :root, notice: "Profile updated"
  end


  private

  def find_user
    @user = User.find(params[:id])
  end

  def update_params
    params.require(:user).permit(:email, :f_name, :l_name, :profile, :avatar, :birthday, :gender, :address_pref, :address_details, :tel)
  end

  def update_params_with_password
    params.require(:user).permit(:email, :f_name, :l_name, :profile, :avatar, :birthday, :gender, :password , :password_confirmation, :address_pref, :address_details, :tel)
  end

end

trip/app/helpers/users/mylists_helper.rb
module Users::MylistsHelper
end

trip/app/helpers/users_helper.rb
module UsersHelper
end

trip/app/views/users/edit.html.haml
.useredit__container
  .useredit__container-box
    .useredit__container-menu
      %ul.useredit__container-menu-ul
        %li.useredit__container-menu-li.useredit__container-menu-li-active
          = link_to "プロフィール設定","javascript:void(0)",class: "useredit__container-menu-li-text"
        %li.useredit__container-menu-li
          = link_to "個人情報","javascript:void(0)",class: "useredit__container-menu-li-text"
        %li.useredit__container-menu-li
          = link_to "アカウント設定","javascript:void(0)",class: "useredit__container-menu-li-text"
        %li.useredit__container-menu-li
          = link_to "パスワード設定","javascript:void(0)",class: "useredit__container-menu-li-text"
    .useredit__container-main
      .useredit__container-main-box
      = form_for(current_user, html: {class: "useredit__container-form"}) do |f|
        .useredit__container-form-list
          .useredit__container-form-list-profile
            %h3.useredit__container-form-title 名前
            = f.text_field :f_name, placeholder: "性", required: :required, class: "useredit__container-form-text"
            = f.text_field :l_name, placeholder: "名", required: :required, class: "useredit__container-form-text"
            .useredit__container-form-list-avatar
              .useredit__container-form-avatar-box
                %h3.useredit__container-form-title プロフィール写真
                .useredit__container-form-avatar-imgbox
                  = image_tag(current_user.avatar,class: "useredit__container-form-avatar-imgbox-img")
                .useredit__container-form-avatar-text
                  顔写真は旅行者がお互いを知るためにとても重要な要素です。あなたのことがはっきりわかる、最高のプロフィール写真を選びましょう！
                .useredit__container-form-avatar-file
                  = f.file_field :avatar,id: "avatar_image"
            %h3.useredit__container-form-title 性別
            %label
              = f.radio_button(:gender, "male" , :checked => @user.gender == "male" )
              男性
            %label
              = f.radio_button(:gender, "female" , :checked => @user.gender == "female" )
              女性
            %h3.useredit__container-form-title 誕生日
            = raw sprintf(f.date_select(:birthday, use_month_numbers: true, start_year: 1916, end_year:(Time.now.year), include_blank: true , date_separator:'%s' ),'年 ', '月 ') + '日'
            %h3.useredit__container-form-title 自己紹介
            = f.text_area :profile, placeholder: "好きにいれてね。", class: "useredit__container-form-text_profile"
          .useredit__container-form-list-private.display-none
            %h3.useredit__container-form-title 住所（都道府県）
            = f.text_field :address_pref, class: "useredit__container-form-text"
            %h3.useredit__container-form-title 住所（市区町村）
            = f.text_field :address_details, class: "useredit__container-form-text"
            %h3.useredit__container-form-title Tel
            = f.text_field :tel, class: "useredit__container-form-text"
          .useredit__container-form-list-account.display-none
            %h3.useredit__container-form-title メールアドレス
            = f.email_field :email, placeholder: "メールアドレス", required: :required, class: "useredit__container-form-text"
          .useredit__container-form-list-password.display-none
            %h3.useredit__container-form-title パスワード
            = f.password_field :password, placeholder: "パスワード(変更する場合のみ)", autocomplete: "off",class: "useredit__container-form-text"
            = f.password_field :password_confirmation, placeholder: "パスワードを再入力(変更する場合のみ)", autocomplete: "off", class: "useredit__container-form-text"
        .useredit__container-form-list-submit
          = f.submit "保存する", class: "useredit__container-form-list-submit-btn"

trip/app/views/users/show.html.haml
.user__container
  .user__container-profile
    .user__container-profile-cover
      = image_tag("profile_cover.jpg",class: "user__container-profile-cover-img")
    .user__container-profile-infos-upper
      .user__container-profile-infos-avatar
        = image_tag("#{@user.avatar}",class: "user__container-profile-infos-avatar-img")
      .user__container-profile-infos-fullname
        = @user.fullname
      .user__container-profile-infos-statuses
        .user__container-profile-infos-statuses-status
          .user__container-profile-infos-statuses-status-sum
            .user__container-profile-infos-statuses-status-text
              = @events.count
          .user__container-profile-infos-statuses-status-label 参加した企画
        .user__container-profile-infos-statuses-status
          .user__container-profile-infos-statuses-status-sum
            .user__container-profile-infos-statuses-status-text
              = @user.attends_count - @events.count
          .user__container-profile-infos-statuses-status-label 申込中の企画
        .user__container-profile-infos-statuses-status
          .user__container-profile-infos-statuses-status-sum
            .user__container-profile-infos-statuses-status-text
              = @user.favorites_count
          .user__container-profile-infos-statuses-status-label お気に入り企画
        .user__container-profile-infos-statuses-status
          .user__container-profile-infos-statuses-status-sum
            .user__container-profile-infos-statuses-status-text
              = @user.events.count
          .user__container-profile-infos-statuses-status-label 作成した企画
    .user__container-profile-infos-lower
      .user__container-profile-infos-lower-list
        %h2.user__container-profile-infos-lower-title 性別
        %p.user__container-profile-infos-lower-desc
          %span.user__container-profile-infos-lower-desc-span
            - if @user.gender.present?
              = @user.gender == "male" ? "男性" : "女性"
            - else
              未設定
        %h2.user__container-profile-infos-lower-title 誕生日
        %p.user__container-profile-infos-lower-desc
          %span.user__container-profile-infos-lower-desc-span
            - if @user.birthday.present?
              = @user.birthday
            - else
              未設定
        %h2.user__container-profile-infos-lower-title 自己紹介
        %p.user__container-profile-infos-lower-desc
          %span.user__container-profile-infos-lower-desc-span
            - if @user.profile.present?
              = @user.profile
            - else
              未設定
  .user__container-mylist
    .user__container-mylist-tabs
      %ul.user__container-mylist-ul
        %li.user__container-mylist-li.user__container-mylist-li-active
          = link_to "参加済",  users_mylist_path(@user.id, list_name: "attended"), remote: true, class: "user__container-mylist-text"
        %li.user__container-mylist-li
          = link_to "申込中",  users_mylist_path(@user.id, list_name: "apply"), remote: true, class: "user__container-mylist-text"
        %li.user__container-mylist-li
          = link_to "お気に入り", users_mylist_path(@user.id, list_name: "fav"), remote: true, class: "user__container-mylist-text"
        %li.user__container-mylist-li
          = link_to "作成",  users_mylist_path(@user.id, list_name: "producer"), remote: true, class: "user__container-mylist-text"
    .user__container-mylist-events
      .user__container-mylist-events-box
        .user__container-mylist-events-contents
          = render partial: 'layouts/event_tile', collection: @events, as: :event
        .user__container-mylist-events-contents-paginate
          = paginate @events, :remote => true