trip/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'events#index'

  resources :events do
    scope module: :events do
      resources :attends, only: [:new, :create, :destroy]
      resources :favorites, only: [:create, :destroy]
      resources :details_images, only: [:create, :destroy]
    end
  end

  resources :users, only: [:show, :edit, :update]

  namespace :users do
    resources :mylists, only: [:show]
  end

  post 'search', to: 'search#index'
  get 'search', to: 'search#index'

  resources :places, only: [:index]

  post 'line_callback', to: "line#callback"

end

trip/app/views/layouts/_event_apply_comments.html.haml
.eventshow__modal-comments
  = link_to image_tag(user.user.avatar, class: "eventshow__modal-comments-avatar"), user_path(user.user_id)
  = link_to "#{user.user.fullname}", class: ".eventshow__modal-comments-name"
  .eventshow__modal-comments-text
    = user.comment

trip/app/views/layouts/_event_dest_search.html.haml
.eventnew__modal.display-none
  .eventnew__modal-main
    .eventnew__modal-header
      .eventnew__modal-headline
        %span.eventnew__modal-headline-text
          開催地の検索
    %section.eventnew__modal-body
      .eventnew__modal-search
        = text_field_tag :keyword, "", class: "eventnew__modal-search-input", placeholder: "県や国名を入力"
        %br/
        %br/
        候補地が表示されたらクリックして選択します。
      .eventnew__modal-desc
        %span.eventnew__modal-desc-text
          = "----- 候補地一覧 -----"
      .eventnew__modal-search
        %ul.eventnew__modal-search-list
    = link_to "とじる", "javascript:void(0)", class: "eventnew__modal-close"

trip/app/views/layouts/_event_rectangle.html.haml
- if Time.now.between?(event.apply_start_date,event.apply_end_date )
  .eventsearch__container-event
    .eventsearch__container-event-imgbox
      = link_to "",event_path(event.id), class: "eventsearch__container-event-imgbox-link", style: "background-image: url(#{event.image});"
      .eventsearch__container-event-status
        %span.eventsearch__container-event-status-span
          申込み受付中
    .eventsearch__container-event-content
      = link_to "#{event.title}", event_path(event.id), class: "eventsearch__container-event-content-title", "data-dest": "#{event.dest}"
      .eventsearch__container-event-content-summary
        = event.summary
      .eventsearch__container-event-content-producer
        = link_to "主催者: #{event.user.fullname}", user_path(event.user.id), class: "eventsearch__container-event-content-producer-text"
      .eventsearch__container-event-content-schedule
        = "開催: #{event.start_date} から #{event.end_date}"
- else
  .eventsearch__container-event
    .eventsearch__container-event-imgbox
      = link_to "",event_path(event.id), class: "eventsearch__container-event-imgbox-link", style: "background-image: url(#{event.image});"
      .eventsearch__container-event-status
        %span.eventsearch__container-event-status-span
          - if event.end_date < Time.now
            企画終了
          - else
            申込み受付前
    .eventsearch__container-event-content
      = link_to "#{event.title}", event_path(event.id), class: "eventsearch__container-event-content-title"
      .eventsearch__container-event-content-summary
        = event.summary
      .eventsearch__container-event-content-producer
        = link_to "主催者#{event.user.fullname}", user_path(event.user.id), class: "eventsearch__container-event-content-producer-text"
      .eventsearch__container-event-content-schedule
        = "開催#{event.start_date} から #{event.end_date}"

trip/app/views/layouts/_event_summary_image.html.haml
%li.eventedit__container-details-md-file
  .eventedit__container-details-md-file-box
    %img.eventedit__container-details-md-file-img{src: "#{image.photo}", value: "#{image.photo.file.filename}"}
  .eventedit__container-details-md-file-btn-insert
    = link_to "画像を挿入", "javascript:void(0)", class: "eventedit__container-details-md-file-btn-insert-text"
  .eventedit__container-details-md-file-btn-delete
    = link_to "画像を削除", event_details_image_path(event.id, image.id), remote: true, method: :delete, class: "eventedit__container-details-md-file-btn-delete-text"
  .eventedit__container-details-md-file-btn-name
    %a.eventedit__container-details-md-file-btn-name
      [ファイル名]
      %br/
      = image.photo.file.filename

trip/app/views/layouts/_event_tile.html.haml
- if Time.now.between?(event.apply_start_date,event.apply_end_date )
  .event__container-event-open
    = link_to "",event_path(event.id), class: "event__container-event-image", style: "background-image: url(#{event.image});"
    .event__container-event-status
      申込み受付中
    .event__container-event-content
      = link_to image_tag(event.user.avatar, class: "event__container-event-content-avatar"), user_path(event.user.id)
      = link_to "#{event.title}", event_path(event.id), class: "event__container-event-content-title"
      = link_to "開催#{event.start_date} から #{event.end_date}", event_path(event.id), class: "event__container-event-content-schedule"
      %span.event__container-event-content-attend
        %i.event__container-event-content-attend-ico
        = event.attends_count
- else
  .event__container-event-close
    = link_to "",event_path(event.id), class: "event__container-event-image", style: "background-image: url(#{event.image});"
    .event__container-event-status
      - if event.end_date < Time.now
        企画終了
      - else
        申込み受付前
    .event__container-event-content
      = link_to image_tag(event.user.avatar, class: "event__container-event-content-avatar"), user_path(event.user.id)
      = link_to "#{event.title}", event_path(event.id), class: "event__container-event-content-title"
      = link_to "開催#{event.start_date} から #{event.end_date}", event_path(event.id), class: "event__container-event-content-schedule"
      %span.event__container-event-content-attend
        %i.event__container-event-content-attend-ico
        = event.attends_count

trip/app/views/layouts/_favorite.html.haml
- if event.favorites.find_by(user_id: current_user.id).present?
  = link_to(event_favorite_path(event.id, event.favorites.find_by(user_id: current_user.id)), remote: true, method: :delete, class: "eventshow__container-side-fav-btn") do
    %span.eventshow__container-side-fav-span
      %i.eventshow__container-side-fav-ico-on
      お気に入りを解除
- else
  = link_to(event_favorites_path(event.id), remote: true, method: :post, class: "eventshow__container-side-fav-btn") do
    %span.eventshow__container-side-fav-span
      %i.eventshow__container-side-fav-ico-off
      お気に入り

trip/app/views/layouts/_footer.html.haml
%footer
  .footer-menu
    = link_to "Trippiece Copy Traing Site","#"

trip/app/views/layouts/_header.html.haml
%header
  .header-container
    %h1.header-logo
      = link_to image_tag("wide_s.png",class: "header-logo"),root_path
    %nav.header-nav
      .header-nav-search
        = form_tag(search_path, method: :post, class: "header-nav-search-form") do
          = text_field_tag :text, "", class: "header-nav-search-input", placeholder: "旅を探そう！"
          .header-nav-search-box.display-none
            .header-nav-search-date
              %label.header-nav-search-date-label
                開催日
              = text_field_tag 'start_date', "", class: "header-nav-search-date-start-input", placeholder: "年/月/日"
              %span
                から
              = text_field_tag 'end_date',"" ,class: "header-nav-search-date-end-input", placeholder: "年/月/日"
            = submit_tag "検索", class: "header-nav-search-btn"
      %ul.header-nav-menu-ul
        %li.header-nav-menu-li
          %ul.header-nav-menu-dropdown-ul.display-none
            %li.header-nav-menu-dropdown-li
              = link_to "プロフィール", user_path(current_user.id), class: "header-nav-menu-dropdown-li-text"
            %li.header-nav-menu-dropdown-li
              = link_to "設定", edit_user_path(current_user.id), class: "header-nav-menu-dropdown-li-text"
            %li.header-nav-menu-dropdown-li
              = link_to "ログアウト", "#{destroy_user_session_path}", method: :delete, class: "header-nav-menu-dropdown-li-text"
          .header-nav-avatar
            = link_to image_tag(current_user.avatar, class: "header-nav-avatar-img")," javascript:void(0)", id: "js-navbar-dropdown"
          %span.header-nav-avatar-span ▼
      = link_to "企画を作成", new_event_path, class: "header-nav-event"
      = link_to image_tag("https://scdn.line-apps.com/n/line_add_friends/btn/ja.png", height: "36px", border: "0", alt: "友達追加"), "https://line.me/R/ti/p/%40fjd4227a"
  = render 'layouts/messages'

trip/app/views/layouts/_header_no_login_event_show.html.haml
%header
  .header-container
    %h1.header-logo
      = link_to image_tag("wide_s.png",class: "header-logo"),root_path
    %nav.header-nav
      = link_to "会員登録（無料）", new_user_registration_path, class: "header-nav-event"
      = link_to "ログイン", new_user_session_path, class: "header-nav-event"

trip/app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
  	<a href="#" data-dismiss="alert" class="close">×</a>
  	<ul>
	  <% if value.instance_of?(Array) %>
		  <% value.each do |msg| %>
		  <li>
		    <%= msg %>
		  </li>
		  <% end %>
		<% elsif %>
	  	<li>
		  	<%= value %>
		  </li>
	  <% end %>
		</ul>
  </div>
<% end %>

trip/app/views/layouts/_welcome.haml
.welcome-container
  .welcome-container-logo
  .welcome-container-main
    %h1.welcome-container-title
      .welcome-container-title-box
    %h2.welcome-container-catchcopy
      どこにもない旅を、みんなでつくる。
      %br/
      trippiece <トリッピース>
    .welcome-container-account
      = link_to image_tag("register_mail.png", width: "280px"),"#{new_user_registration_path}"
      .welcome-container-account-signup
      .welcome-container-account-signin
        = link_to "すでにユーザーの方はこちら", "#{new_user_session_path}",{class: "welcome-container-account-signin-text"}
      = link_to image_tag("https://scdn.line-apps.com/n/line_add_friends/btn/ja.png", height: "36px", border: "0", alt: "友達追加"), "https://line.me/R/ti/p/%40fjd4227a"
%h3.welcome-container-recommend おすすめの企画

trip/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8 noindex", "http-equiv" => "Content-Type", :name => "robots"}/
    %title Traning site トリッピース
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyCv_vJOYoOt9ovvUxHvCrUx0ZjsVMWwJqY&callback=initMap"}
  %body
    #loading
      = image_tag("#{ image_path "gif-load.gif"}", id: "page_load")
    - if user_signed_in?
      = render "layouts/header"
    = yield
    = render "layouts/footer"