trip/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'events#index'

  resources :events do
    scope module: :events do
      resources :attends, only: [:new, :create, :destroy]
      resources :favorites, only: [:create, :destroy]
      resources :details_images, only: [:create, :destroy]
    end
  end

  resources :users, only: [:show, :edit, :update]

  namespace :users do
    resources :mylists, only: [:show]
  end

  post 'search', to: 'search#index'
  get 'search', to: 'search#index'

  resources :places, only: [:index]

  post 'line_callback', to: "line#callback"

end

trip/app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user

  has_many :attends
  has_many :favorites
  has_many :details_images, dependent: :destroy

  mount_uploader :image, SummaryImageUploader

  validates :end_date, presence: true
  validates :dest, presence: true
  validates :apply_end_date, presence: true
  validate  :apply_date_check
  validate  :apply_term_check
  validate  :start_end_term_check

  enum status: { open: 0, draft: 1 }

  # カスタムバリデーション
  # 申し込み開始日のチェック
  def apply_date_check
    if apply_start_date and end_date < apply_start_date
      errors.add(:apply_start_date, "can't be in the past than end_date")
    end
  end

  # applyのendがstartより後かどうか
  def apply_term_check
    if apply_start_date and apply_start_date > apply_end_date
      errors.add(:apply_end_date, "can't be in the past than apply_start_date")
    end
  end

  # endがstartより後かどうか
  def start_end_term_check
    if start_date and start_date > end_date
      errors.add(:end_date, "can't be in the past than start_date")
    end
  end

  # --- クエリ スコープ ---
  # title、summary、destカラムの部分検索
  scope :text_like, -> text {
    where('title like ? or summary like ? or dest like ?', "%#{text}%", "%#{text}%", "%#{text}%") if text.present?
  }
  # 開催日の検索
  scope :date_between, -> from, to {
    if from.present? && to.present?
      where(start_date: from..to)
    elsif from.present?
      where('start_date >= ?', from)
    elsif to.present?
      where('start_date <= ?', to)
    end
  }

  # 申込み日のスタート日の検索
  scope :apply_start_date_between, -> from, to {
    if from.present? && to.present?
      where(apply_start_date: from..to)
    elsif from.present?
      where('apply_start_date >= ?', from)
    elsif to.present?
      where('apply_start_date <= ?', to)
    end
  }

  # 申込み日の終わりの検索
  scope :apply_end_date_between, -> from, to {
    if from.present? && to.present?
      where(apply_end_date: from..to)
    elsif from.present?
      where('apply_end_date >= ?', from)
    elsif to.present?
      where('apply_end_date <= ?', to)
    end
  }

end

trip/app/controllers/events/attends_controller.rb
class Events::AttendsController < ApplicationController

  before_action :authenticate_user!, only: [:new,:create]

  def new
    @attend = Attend.new
    find_event_id
  end

  def create
    find_user
    @attend = Attend.new(create_params_attend)
    if @user.update(update_params_user) && @attend.save
      flash[:notice] = "#{Event.find(params[:event_id]).title}に申込みました。"
      redirect_to root_path
    elsif @attend.errors.present?
      flash[:error] = @attend.errors.full_messages
      redirect_to :back and return
    elsif @user.errors.present?
      flash[:error] = @user.errors.full_messages
      redirect_to :back and return
    end
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "企画が見つかりませんでした。"
      redirect_to root_path
  end

  private

  def create_params_attend
    params.require(:attend).permit(:comment).merge(user_id: current_user.id, event_id: params[:event_id] )
  end

  def update_params_user
    params.require(:user).permit(:f_name, :l_name, :profile, :birthday, :gender, :address_pref, :address_details, :tel)
  end

  def find_event_id
    @event = Event.find(params[:event_id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "企画が見つかりませんでした。"
    redirect_to root_path
  end

  def find_user
    @user = User.find(current_user.id)
  end

end

trip/app/controllers/events/details_images_controller.rb
class Events::DetailsImagesController < ApplicationController

  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    respond_to do |format|
      format.js {
        @images = DetailsImage.new(create_params)
        if @images.save
          @event = Event.find(params[:event_id])
        else
          @event = Event.find(params[:event_id])
        end
      }
    end
  end

  def destroy
    DetailsImage.find(params[:id]).destroy
    @event = Event.find(params[:event_id])
    respond_to do |format|
      format.js
    end
  end

  def create_params
    params.permit(:photo, :event_id)
  end

end

trip/app/controllers/events/favorites_controller.rb
class Events::FavoritesController < ApplicationController

  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    Favorite.create(create_params)
    @event = Event.find(params[:event_id])
  end

  def destroy
    Favorite.find(params[:id]).destroy
    @event = Event.find(params[:event_id])
  end

  private
  def create_params
    params.permit(:event_id).merge(user_id: current_user.id)
  end

end

trip/app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, only: [:new,:create,:edit,:update,:destroy]

  def index
    respond_to do |format|
      format.html {
        if params[:sort].blank?
          @events = Event.order('id DESC').open.page(params[:page])
          @sort_now = "新着順"
        elsif params[:sort] == "new"
          @events = Event.order('id DESC').open.page(params[:page])
          @sort_now = "新着順"
        else
          @events = Event.order('start_date').open.page(params[:page])
          @sort_now = "開催日"
        end
        @nav_event_list = Event.apply_end_date_between(Time.now,"").order(:apply_end_date).open.limit(5)
      }
      format.js {
        if params[:new].present?
          @events = Event.order('id DESC').open.page(params[:new])
        elsif params[:start_date].present?
          @events = Event.order('start_date').open.page(params[:start_date])
        end
      }
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(create_params)
    if @event.save
      redirect_to(edit_event_url(@event.id))
    else
      flash[:error] = @event.errors.full_messages
      redirect_to :back and return
    end
  end

  def show
    respond_to do |format|
      format.html {
        find_event_id
      }
      format.js {
        @event_attend_list = Event.find(params[:id]).attends.page(params[:page])
      }
    end
  end

  def edit
    find_event_id
    @details_images = DetailsImage.new
  end

  def update
    find_event_id
    if @event.update(update_params)
      flash[:notice] = "企画が公開されました" if @event.status == 0
      flash[:notice] = "企画を下書き保存しました" if @event.status == 1
    else
      flash[:error] = @event.errors.full_messages
      redirect_to :back and return
    end
    redirect_to root_path
  end

  def destroy
    find_event_id
    if @event.destroy
      flash[:notice] = "企画を削除しました。"
    else
      flash[:error] = "企画を削除できませんでした。"
    end
    redirect_to root_path
  end


  private

  def create_params
    @event_status = { status: 1 }
    params.require(:event).permit(:start_date, :end_date, :dest, :apply_start_date, :apply_end_date).merge(user_id: current_user.id).merge(@event_status)
  end

  def update_params
    if params[:open].present?
      @event_status = { status: 0 }
    elsif params[:draft].present?
      @event_status = { status: 1 }
    end
    params.require(:event).permit(:title, :start_date, :end_date, :apply_start_date, :apply_end_date, :summary, :details, :status, :image, :dest, :price).merge(@event_status)
  end

  def find_event_id
    @event = Event.includes(:user).find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "企画が見つかりませんでした。"
    redirect_to root_path
  end

end

trip/app/helpers/events/attends_helper.rb
module Events::AttendsHelper
end

trip/app/helpers/events/details_images_helper.rb
module Events::DetailsImagesHelper
end

trip/app/helpers/events/favorites_helper.rb
module Events::FavoritesHelper
end

trip/app/helpers/events_helper.rb
module EventsHelper
end

trip/app/views/events/edit.html.haml
.eventedit__container
  = form_for(@event, html: {class: "eventedit__container-form"}) do |f|
    .eventedit__container-header
      .eventedit__container-header-menu
        .eventedit__container-header-columns
          .eventedit__container-header-columns-status
            %a.eventedit__container-header-columns-status-text
              現在のステータス
              %br/
              - if @event.status == "open"
                %span.eventedit__container-header-columns-status-span
                  企画公開中！
              - else
                %span.eventedit__container-header-columns-status-span
                  下書き保存中
          .eventedit__container-header-columns-action
            = f.submit "公開", name: "open", class: "eventedit__container-header-columns-action-open"
            = f.submit "下書き保存", name: "draft", class: "eventedit__container-header-columns-action-close"
            .eventedit__container-header-columns-action-delete-box
              = link_to "企画を削除する", event_path(@event.id), method: :delete, class: "eventedit__container-header-columns-action-delete-text"
    .eventedit__container-main
      .eventedit__container-box
        .eventedit__container-form-box
          %p.eventedit__container-form-comment
            まずはざっくりと企画の基本情報を入力してみましょう。後から編集もできるので、詳細が決まったらどんどん編集して、企画ページを充実させていきましょう！
          %section.eventedit__container-section-title
            .eventedit__container-title-box
              = f.text_field :title, placeholder: "北海道・東北へ行こう！", class: "eventedit__container-title-input", required: :required
              %p.eventedit__container-title-desc
            .eventedit__container-title-label
              .eventedit__container-title-label-osbox
                .eventedit__container-title-label-isbox
                  タイトル
          %section.eventedit__container-section-basic
            .eventedit__container-section-basic-main
              .eventedit__container-section-basic-main-box
                .eventedit__container-img{style: "background-image: image-url(#{@event.image})"}
                  .eventedit__container-img-msgbox
                    .eventedit__container-img-btnbox
                      アップロードする
                      = f.file_field :image, class:"eventedit__container-img-btn", id: "js-event-image"
                .eventedit__container-infobar
                  .eventedit__container-producer
                    .eventedit__container-producer-avatar
                      = image_tag "#{current_user.avatar}", class: "eventedit__container-producer-avatar-img"
                    %span.eventedit__container-producer-avatar-span
                      = current_user.fullname
                  .eventedit__container-info
                    .eventedit__container-fav
                      %i.eventedit__container-fav-ico
                      %span.eventedit__container-fav-sum 0
                    .eventedit__container-attend
                      %i.eventedit__container-attend-ico
                      %span.eventedit__container-attend-sum 0
                .eventedit__container-summary
                  = f.text_area :summary, class: "eventedit__container-summary-text", placeholder: "例）2〜3月に転職するタイミングで、憧れのウユニ塩湖に行きたいと思っています！南米に一人で行くのは不安なので、一緒に行ける旅仲間を募集しています。一緒に、ウユニ塩湖の絶景に感動して、写真を撮って遊びましょう！", required: :required
                  / .eventedit__container-hashtag
                  /   .eventedit__container-hashtag-desc
                  /     ハッシュタグを追加
                  /   %a.eventedit__container-hashtag-tag #アラサー歓迎
                  /   %a.eventedit__container-hashtag-tag #20代歓迎
                  /   %a.eventedit__container-hashtag-tag #40代以上歓迎
                  %p.eventedit__container-summary-countchar
            .eventedit__container-basic-side
              .eventedit__container-basic-side-box
                .eventedit__container-img-label
                  .eventedit__container-img-label-box
                    企画の画像
                .eventedit__container-summary-label
                  .eventedit__container-summary-label-box
                    旅への想い
          %section.eventedit__container-section-desc
            .eventedit__container-section-desc-main
              .eventedit__container-section-desc-main-box
                .eventedit__container-schedule
                  #js-event-dest-map
                  %table.eventedit__container-schedule-table
                    %tbody.eventedit__container-schedule-tbody
                      %tr.eventedit__container-schedule-tr
                        %th.eventedit__container-schedule-th
                          参加受付期間
                        %td.eventedit__container-schedule-td
                          %span.eventedit__container-schedule-td-span 開始日
                          .eventedit__container-schedule-td-date
                            = raw sprintf(f.date_select(:apply_start_date, use_month_numbers: true, start_year: (Time.now.year) , default: Time.now , date_separator:'%s' ),'年 ', '月 ') + '日'
                          %br
                          %span.eventedit__container-schedule-td-span 終了日
                          .eventedit__container-schedule-td-date
                            = raw sprintf(f.date_select(:apply_end_date, use_month_numbers: true, start_year: (Time.now.year) ,default: Time.now + 2.week , date_separator:'%s' ),'年 ', '月 ') + '日'
                      %tr.eventedit__container-schedule-tr
                        %th.eventedit__container-schedule-th
                          日程
                        %td.eventedit__container-schedule-td
                          %span.eventedit__container-schedule-td-span 開始日
                          .eventedit__container-schedule-td-date
                            = raw sprintf(f.date_select(:start_date, use_month_numbers: true, start_year: (Time.now.year), default: Time.now + 1.month , date_separator:'%s' ),'年 ', '月 ') + '日'
                          %br
                          %span.eventedit__container-schedule-td-span 終了日
                          .eventedit__container-schedule-td-date
                            = raw sprintf(f.date_select(:end_date, use_month_numbers: true, start_year: (Time.now.year), default: Time.now + 1.month , date_separator:'%s' ),'年 ', '月 ') + '日'
                      %tr.eventedit__container-schedule-tr
                        %th.eventedit__container-schedule-th
                          行き先
                        %td.eventedit__container-schedule-td
                          .eventnew__container-basic-dest
                            %span.eventnew__container-basic-dest-text#js-event-dest-text
                              = @event.dest
                            %button.eventnew__container-basic-dest-btn
                              設定する
                            = f.hidden_field :dest, value: "#{@event.dest}", id: "js-dest-value"
                      = render partial: 'layouts/event_dest_search'
                      %tr.eventedit__container-schedule-tr
                        %th.eventedit__container-schedule-th
                          予定金額
                        %td.eventedit__container-schedule-td
                          = f.text_field :price, class: "eventedit__container-price-input"
                  .eventedit__container-details-headline
                    = link_to "編集","javascript:void(0)", class: "eventedit__container-details-headline-switch-edit"
                    = link_to "プレビュー","javascript:void(0)", class: "eventedit__container-details-headline-switch-prev"
                  .eventedit__container-details-body
                    .eventedit__container-details-md-box
                      .eventedit__container-details-md-headline
                        = link_to "見出しを挿入する","javascript:void(0)", class:"eventedit__container-details-md-headline-text"
                        %span.eventedit__container-details-md-fileup
                          挿入する画像をアップロード
                          = file_field_tag :photo, id: "js-form-file" ,class: "eventedit__container-details-md-fileup-input"
                        = hidden_field_tag :event_id, @event.id , id: "js-form-event_id"
                        %ul.eventedit__container-details-md-files
                          = render partial: "layouts/event_summary_image", locals: { event: @event }, collection: @event.details_images, as: :image
                    .eventedit__container-details-body-box
                      = f.text_area :details, class: "eventedit__container-details-body-text"
                .eventedit__container-details-markdown.display-none
                  .eventedit__container-details-markdown-prev
                    = markdown(@event.details)
            .eventedit__container-section-desc-side
              .eventedit__container-section-desc-side-box
                .eventedit__container-schedule-label
                  .eventedit__container-schedule-label-box
                    日程
                .eventedit__container-dest-label
                  .eventedit__container-dest-label-box
                    行き先
                .eventedit__container-price-label
                  .eventedit__container-price-label-box
                    予定金額
                .eventedit__container-details-label
                  .eventedit__container-details-label-box
                    詳細
        .eventedit__container-form-submit
          %p.eventedit__container-form-submit-text
            保存するとこの企画が全体公開となります。公開しない場合は「下書き保存する」ボタンをクリックしてください。
          = f.submit "公開", name: "open", class: "eventedit__container-form-submit-btn-public"
          = f.submit "下書き保存", name: "draft", class: "eventedit__container-form-submit-btn-draft"

trip/app/views/events/index.html.haml
- if user_signed_in?
  .top__container
    .top__container-banner
      .top__container-banner-box
        - @nav_event_list.each do |ev|
          = link_to(event_path(ev.id),class: "top__container-banner-campaign-main") do
            .top__container-banner-campaign-main-img{style: "background-image:url(#{asset_path ev.image});"}
              .top__container-banner-campaign-main-title
                = ev.title
  .top__container-nav
    .top__container-banner-campaign-list
      - @nav_event_list.each do |ev|
        .top__container-banner-campaign-sub{style: "background-image:url(#{asset_path ev.image});"}
          = link_to "#{ev.title}", "javascript:void(0)", class: "top__container-banner-campaign-sub-title"
    .top__container-banner-campaign-list-text
      締め切り間近の企画
  .top__container-events
    .event__container-headline
      企画一覧
    .event__container-nav
      .event__container-sort
        %span.event__container-sort-now
          = @sort_now
          %span
            ▼
        .event__container-sort-dropdown
          %ul.event__container-sort-dropdown-items.display-none
            %li.event__container-sort-dropdown-item
              = link_to "新着順", events_path(sort: "new")
            %li.event__container-sort-dropdown-item
              = link_to "開催日", events_path(sort: "start_date")
    .event__container
      = render partial: "layouts/event_tile", collection: @events, as: :event
    .event__container-event-more
      - if @sort_now == "新着順"
        = link_to_next_page @events, 'もっとみる', :param_name => :new , :remote => true, class: "event__container-event-more-btn"
      - elsif @sort_now == "開催日"
        = link_to_next_page @events, 'もっとみる', :param_name => :start_date , :remote => true, class: "event__container-event-more-btn"
- else
  = render "layouts/welcome"
  .top__container-events
    .event__container
      = render partial: "layouts/event_tile", collection: @events, as: :event
    .event__container-event-more
      = link_to_next_page @events, 'もっとみる', :param_name => :new , :remote => true, class: "event__container-event-more-btn"

trip/app/views/events/index.js.erb
$(".event__container").append("<%= j(render partial: 'layouts/event_tile', collection: @events, as: :event) %>");
$(".event__container-event-more").html("<%= j(link_to_next_page @events, 'もっとみる', :remote => true,class: "event__container-event-more-btn") %>");

trip/app/views/events/new.html.haml
.eventnew__container
  = form_for(@event, html: {class: "eventnew__container-form"}) do |f|
    .eventnew__container-desc
      .eventnew__container-desc-text
        企画を作成する
      = image_tag "form_step.png", class: "eventnew__container-desc-img"
    .eventnew__container-basic
      .eventnew__container-basic-schedule
        .eventnew__container-basic-main
          %h1.eventnew__container-basic-headline
            %span.eventnew__container-basic-headline-text
          .eventnew__container-basic-date
            %h1.eventnew__container-basic-headline
              参加受付期間
            .eventnew__container-basic-schedule
              %span.eventnew__container-basic-schedule-span 開始日
              .eventnew__container-basic-schedule-date
                = raw sprintf(f.date_select(:apply_start_date, use_month_numbers: true, start_year: (Time.now.year) , default: Time.now , date_separator:'%s' ),'年 ', '月 ') + '日'
              %br
              %span.eventnew__container-basic-schedule-span 終了日
              .eventnew__container-basic-schedule-date
                = raw sprintf(f.date_select(:apply_end_date, use_month_numbers: true, start_year: (Time.now.year), default: Time.now + 2.week , date_separator:'%s' ),'年 ', '月 ') + '日'
        .eventnew__container-basic-tips
          .eventnew__container-basic-text
            参加を受け付ける期間を入力してください。
      .eventnew__container-basic-schedule
        .eventnew__container-basic-main
          %h1.eventnew__container-basic-headline
            %span.eventnew__container-basic-headline-text
          .eventnew__container-basic-date
            %h1.eventnew__container-basic-headline
              日程
            .eventnew__container-basic-schedule
              %span.eventnew__container-basic-schedule-span 開始日
              .eventnew__container-basic-schedule-date
                = raw sprintf(f.date_select(:start_date, use_month_numbers: true, start_year: (Time.now.year), default: Time.now + 1.month , date_separator:'%s' ),'年 ', '月 ') + '日'
              %br
              %span.eventnew__container-basic-schedule-span 終了日
              .eventnew__container-basic-schedule-date
                = raw sprintf(f.date_select(:end_date, use_month_numbers: true, start_year: (Time.now.year), default: Time.now + 1.month + 1.day , date_separator:'%s' ),'年 ', '月 ') + '日'
        .eventnew__container-basic-tips
          .eventnew__container-basic-text
            開催期間を入力してください。不明の場合は暫定の日にちとしてください。
      .eventnew__container-basic-dest
        .eventnew__container-basic-main
          %h1.eventnew__container-basic-headline
            行き先
          .eventnew__container-basic-dest
            %span.eventnew__container-basic-dest-text
              設定されていません。
            %button.eventnew__container-basic-dest-btn
              設定する
            = f.hidden_field :dest, value: "", id: "js-dest-value"
      = render partial: 'layouts/event_dest_search'
      .eventnew__container-basic-tips
        .eventnew__container-basic-text
          行き先を設定しましょう。
    .eventnew__container-form-submit
      = f.submit "詳細入力画面へ", name: "draft", class: "eventnew__container-form-submit-btn"

trip/app/views/events/show.html.haml
- unless user_signed_in?
  = render partial: "layouts/header_no_login_event_show"
.eventshow__container
  .eventshow__container-box
    %article.eventshow__container-article
      .eventshow__container-title
        %h1.eventshow__container-title-text
          = @event.title
      - if user_signed_in?
        %section.eventshow__container-tab
          - if @event.user.id == current_user.id
            = link_to "企画を管理・編集", edit_event_path(@event.id), class: "eventshow__container-tab-edit"
          = link_to "申込者一覧" , event_path(@event.id), :remote => true, class: "eventshow__container-tab-apply"
      %section.eventshow__container-main
        .eventshow__container-main-box
          .eventshow__container-basic
            .eventshow__container-img
              .eventshow__container-img-box
                = image_tag "#{@event.image}", class:"eventshow__container-img-image"
            .eventshow__container-infobar
              .eventshow__container-producer
                .eventshow__container-producer-avatar
                  = image_tag "#{@event.user.avatar}", class: "eventshow__container-producer-avatar-img"
                %span.eventshow__container-producer-avatar-span
                  = @event.user.fullname
              .eventshow__container-info
                .eventshow__container-fav
                  %i.eventshow__container-fav-ico
                  %span.eventshow__container-fav-sum
                    = @event.favorites_count
                .eventshow__container-attend
                  %i.eventshow__container-attend-ico
                  %span.eventshow__container-attend-sum
                    = @event.attends_count
            .eventshow__container-summary
              %p.eventshow__container-summary-text
                = @event.summary
          .eventshow__container-desc
            .eventshow__container-desc-box
              .eventshow__container-columns
                .eventshow__container-columns-item
                  %h4.eventshow__container-columns-title
                    %span.eventshow__container-columns-span 申込み受付期間
                  %span.eventshow__container-columns-content
                    = @event.apply_start_date
                    から
                    = @event.apply_end_date
                .eventshow__container-columns-item
                  %h4.eventshow__container-columns-title
                    %span.eventshow__container-columns-span 日程
                  %span.eventshow__container-columns-content
                    = @event.start_date
                    から
                    = @event.end_date
                .eventshow__container-columns-item
                  %h4.eventshow__container-columns-title
                    %span.eventshow__container-columns-span 行き先
                  %span.eventshow__container-columns-content#js-event-dest-text
                    = @event.dest
              #js-event-dest-map
              %h4.eventshow__container-columns-title
                %span.eventshow__container-columns-span 予定金額
              %span.eventshow__container-columns-content
                = "#{(@event.price).to_s(:delimited)}"
                円
              %h4.eventshow__container-columns-details
                %span.eventshow__container-columns-span
                  %br/
                  詳細
              .eventshow__container-details
                = markdown(@event.details)
      .eventshow__modal.display-none
        .eventshow__modal-main
          .eventshow__modal-header
            .eventshow__modal-headline
              %span.eventshow__modal-headline-text
                申込み中のユーザー
          %section.eventshow__modal-body
            .eventshow__modal-sum
              .eventshow__modal-sum-box
                .eventshow__modal-sum-value
                  = @event.attends_count
                .eventshow__modal-sum-label
                  参加者数
            .eventshow__modal-desc
              %span.eventshow__modal-desc-text
                = "----- 参加者一覧 -----"
            .eventshow__modal-comments-render
          .event__container-event-more
          = link_to "とじる", "javascript:void(0)", class: "eventshow__modal-close"
      %section.eventshow__container-side
        .eventshow__container-side-box
          .eventshow__container-side-form
            .eventshow__container-side-form-box
              .eventshow__container-side-status
                %h4.eventshow__container-side-status-box
                  %small.eventshow__container-side-status-small
                    企画のステータス
                  %br/
                  %br/
                  - if @event.end_date < Time.now
                    %span.eventshow__container-side-status-span
                      終了しました。
                  - elsif Time.now.between?(@event.apply_start_date,@event.apply_end_date )
                    %span.eventshow__container-side-status-span
                      申込受付中！
                  - else
                    %span.eventshow__container-side-status-span
                      申込受付期間
                    %p.eventshow__container-side-status-term
                      %br/
                      = @event.apply_start_date
                      から
                      = @event.apply_end_date
              - if user_signed_in?
                .eventshow__container-side-attend
                - if Time.now.between?(@event.apply_start_date,@event.apply_end_date )
                  - if current_user.attends.find_by(event_id: @event.id)
                    %a.eventshow__container-side-attend-btn
                      %span.eventshow__container-side-attend-span
                        申し込み済み
                  - else
                    = link_to(new_event_attend_path(@event.id), class: "eventshow__container-side-attend-btn") do
                      %span.eventshow__container-side-attend-span
                        申し込む
                .eventshow__container-side-fav
                  = render partial: "layouts/favorite", locals: { event: @event }
              - else
                .eventshow__container-side-regist
                  = link_to(new_user_registration_path, class: "eventshow__container-side-regist-btn") do
                    %span.eventshow__container-side-regist-span
                      参加するにはこちら（無料登録）

trip/app/views/events/show.js.erb
$(".eventshow__modal-comments-render").append("<%= j(render partial: 'layouts/event_apply_comments', collection: @event_attend_list, as: :user) %>");
$(".event__container-event-more").html("<%= j(link_to_next_page @event_attend_list, 'もっとみる', :remote => true, class: 'event__container-event-more-btn') %>");