trip/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'events#index'

  resources :events do
    scope module: :events do
      resources :attends, only: [:new, :create, :destroy]
      resources :favorites, only: [:create, :destroy]
      resources :details_images, only: [:create, :destroy]
    end
  end

  resources :users, only: [:show, :edit, :update]

  namespace :users do
    resources :mylists, only: [:show]
  end

  post 'search', to: 'search#index'
  get 'search', to: 'search#index'

  resources :places, only: [:index]

  post 'line_callback', to: "line#callback"

end

trip/app/models/attend.rb
class Attend < ActiveRecord::Base

  belongs_to :event, :counter_cache => true
  belongs_to :user, :counter_cache => true

  validates :comment, presence: true

end

trip/app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user

  has_many :attends
  has_many :favorites
  has_many :details_images, dependent: :destroy

  mount_uploader :image, SummaryImageUploader

  validates :end_date, presence: true
  validates :dest, presence: true
  validates :apply_end_date, presence: true
  validate  :apply_date_check
  validate  :apply_term_check
  validate  :start_end_term_check

  enum status: { open: 0, draft: 1 }

  # カスタムバリデーション
  # 申し込み開始日のチェック
  def apply_date_check
    if apply_start_date and end_date < apply_start_date
      errors.add(:apply_start_date, "can't be in the past than end_date")
    end
  end

  # applyのendがstartより後かどうか
  def apply_term_check
    if apply_start_date and apply_start_date > apply_end_date
      errors.add(:apply_end_date, "can't be in the past than apply_start_date")
    end
  end

  # endがstartより後かどうか
  def start_end_term_check
    if start_date and start_date > end_date
      errors.add(:end_date, "can't be in the past than start_date")
    end
  end

  # --- クエリ スコープ ---
  # title、summary、destカラムの部分検索
  scope :text_like, -> text {
    where('title like ? or summary like ? or dest like ?', "%#{text}%", "%#{text}%", "%#{text}%") if text.present?
  }
  # 開催日の検索
  scope :date_between, -> from, to {
    if from.present? && to.present?
      where(start_date: from..to)
    elsif from.present?
      where('start_date >= ?', from)
    elsif to.present?
      where('start_date <= ?', to)
    end
  }

  # 申込み日のスタート日の検索
  scope :apply_start_date_between, -> from, to {
    if from.present? && to.present?
      where(apply_start_date: from..to)
    elsif from.present?
      where('apply_start_date >= ?', from)
    elsif to.present?
      where('apply_start_date <= ?', to)
    end
  }

  # 申込み日の終わりの検索
  scope :apply_end_date_between, -> from, to {
    if from.present? && to.present?
      where(apply_end_date: from..to)
    elsif from.present?
      where('apply_end_date >= ?', from)
    elsif to.present?
      where('apply_end_date <= ?', to)
    end
  }

end

trip/app/controllers/events/attends_controller.rb
class Events::AttendsController < ApplicationController

  before_action :authenticate_user!, only: [:new,:create]

  def new
    @attend = Attend.new
    find_event_id
  end

  def create
    find_user
    @attend = Attend.new(create_params_attend)
    if @user.update(update_params_user) && @attend.save
      flash[:notice] = "#{Event.find(params[:event_id]).title}に申込みました。"
      redirect_to root_path
    elsif @attend.errors.present?
      flash[:error] = @attend.errors.full_messages
      redirect_to :back and return
    elsif @user.errors.present?
      flash[:error] = @user.errors.full_messages
      redirect_to :back and return
    end
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "企画が見つかりませんでした。"
      redirect_to root_path
  end

  private

  def create_params_attend
    params.require(:attend).permit(:comment).merge(user_id: current_user.id, event_id: params[:event_id] )
  end

  def update_params_user
    params.require(:user).permit(:f_name, :l_name, :profile, :birthday, :gender, :address_pref, :address_details, :tel)
  end

  def find_event_id
    @event = Event.find(params[:event_id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "企画が見つかりませんでした。"
    redirect_to root_path
  end

  def find_user
    @user = User.find(current_user.id)
  end

end

trip/app/controllers/events/details_images_controller.rb
class Events::DetailsImagesController < ApplicationController

  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    respond_to do |format|
      format.js {
        @images = DetailsImage.new(create_params)
        if @images.save
          @event = Event.find(params[:event_id])
        else
          @event = Event.find(params[:event_id])
        end
      }
    end
  end

  def destroy
    DetailsImage.find(params[:id]).destroy
    @event = Event.find(params[:event_id])
    respond_to do |format|
      format.js
    end
  end

  def create_params
    params.permit(:photo, :event_id)
  end

end

trip/app/controllers/events/favorites_controller.rb
class Events::FavoritesController < ApplicationController

  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    Favorite.create(create_params)
    @event = Event.find(params[:event_id])
  end

  def destroy
    Favorite.find(params[:id]).destroy
    @event = Event.find(params[:event_id])
  end

  private
  def create_params
    params.permit(:event_id).merge(user_id: current_user.id)
  end

end

trip/app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, only: [:new,:create,:edit,:update,:destroy]

  def index
    respond_to do |format|
      format.html {
        if params[:sort].blank?
          @events = Event.order('id DESC').open.page(params[:page])
          @sort_now = "新着順"
        elsif params[:sort] == "new"
          @events = Event.order('id DESC').open.page(params[:page])
          @sort_now = "新着順"
        else
          @events = Event.order('start_date').open.page(params[:page])
          @sort_now = "開催日"
        end
        @nav_event_list = Event.apply_end_date_between(Time.now,"").order(:apply_end_date).open.limit(5)
      }
      format.js {
        if params[:new].present?
          @events = Event.order('id DESC').open.page(params[:new])
        elsif params[:start_date].present?
          @events = Event.order('start_date').open.page(params[:start_date])
        end
      }
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(create_params)
    if @event.save
      redirect_to(edit_event_url(@event.id))
    else
      flash[:error] = @event.errors.full_messages
      redirect_to :back and return
    end
  end

  def show
    respond_to do |format|
      format.html {
        find_event_id
      }
      format.js {
        @event_attend_list = Event.find(params[:id]).attends.page(params[:page])
      }
    end
  end

  def edit
    find_event_id
    @details_images = DetailsImage.new
  end

  def update
    find_event_id
    if @event.update(update_params)
      flash[:notice] = "企画が公開されました" if @event.status == 0
      flash[:notice] = "企画を下書き保存しました" if @event.status == 1
    else
      flash[:error] = @event.errors.full_messages
      redirect_to :back and return
    end
    redirect_to root_path
  end

  def destroy
    find_event_id
    if @event.destroy
      flash[:notice] = "企画を削除しました。"
    else
      flash[:error] = "企画を削除できませんでした。"
    end
    redirect_to root_path
  end


  private

  def create_params
    @event_status = { status: 1 }
    params.require(:event).permit(:start_date, :end_date, :dest, :apply_start_date, :apply_end_date).merge(user_id: current_user.id).merge(@event_status)
  end

  def update_params
    if params[:open].present?
      @event_status = { status: 0 }
    elsif params[:draft].present?
      @event_status = { status: 1 }
    end
    params.require(:event).permit(:title, :start_date, :end_date, :apply_start_date, :apply_end_date, :summary, :details, :status, :image, :dest, :price).merge(@event_status)
  end

  def find_event_id
    @event = Event.includes(:user).find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "企画が見つかりませんでした。"
    redirect_to root_path
  end

end

trip/app/helpers/events/attends_helper.rb
module Events::AttendsHelper
end

trip/app/helpers/events/details_images_helper.rb
module Events::DetailsImagesHelper
end

trip/app/helpers/events/favorites_helper.rb
module Events::FavoritesHelper
end

trip/app/helpers/events_helper.rb
module EventsHelper
end

trip/app/views/events/attends/new.html.haml
.attendnew__container
  = form_for @attend, url: event_attends_path do |f|
    %section.attendnew__container-cover
      .attendnew__container-cover-img{style: "background-image: url(#{@event.image})"}
      .attendnew__container-cover-title
        = @event.title
    %section.attendnew__container-notice
      %p.attendnew__container-notice-text
        以下の申込みフォームに必要事項をご記入の上、確認ページへお進みください。また、コメントは必ずご記入ください。
    .attendnew__container-step1
      %section.attendnew__container-plan
        .attendnew__container-plan-left
          %section.attendnew__container-schedule
            %h5.attendnew__container-schedule-headline
              日程
            %span.attendnew__container-schedule-desc
              = @event.start_date
              から
              = @event.end_date
          %section.attendnew__container-price
            %h5.attendnew__container-price-headline
              金額
            %span.attendnew__container-price-desc
              = "#{(@event.price).to_s(:delimited)}"
              円
        .attendnew__container-plan-right
          %section.attendnew__container-comment
            %h5.attendnew__container-comment-headline
              一言どうぞ
            %p.attendnew__container-comment-notice
              こちらの意気込みは旅のメンバー一覧に表示されます。
            = f.text_area :comment, placeholder: "コメントは必ずご記入ください。", class:"attendnew__container-comment-textbox", required: :required
      = link_to "申込み者情報の入力へ", "javascript:void(0)", class: "attendnew__container-step1-btn"
    .attendnew__container-step2.display-none
      .attendnew__container-plan
        .attendnew__container-plan-left
          %section.attendnew__container-private
            %p.attendnew__container-private-notice
              こちらで入力した情報はアカウントに保存され、次回以降の申込時に自動で入力されます。
            = fields_for current_user do |u|
              .attendnew__container-form-item
                %h5.attendnew__container-form-title 名字
                = u.text_field :f_name, placeholder: "性", required: :required, class: "attendnew__container-form-text", required: :required
              .attendnew__container-form-item
                %h5.attendnew__container-form-title 名前
                = u.text_field :l_name, placeholder: "名", required: :required, class: "attendnew__container-form-text", required: :required
              .attendnew__container-form-item
                %h5.attendnew__container-form-title 性別
                %label
                  = u.radio_button(:gender, "male" , :checked => current_user.gender == "male" , required: :required)
                  男性
                %label
                  = u.radio_button(:gender, "female" , :checked => current_user.gender == "female" )
                  女性
              .attendnew__container-form-item
                %h5.attendnew__container-form-title 誕生日
                = raw sprintf(u.date_select(:birthday, use_month_numbers: true, start_year: 1916, end_year:(Time.now.year), date_separator:'%s' ),'年 ', '月 ') + '日'
              .attendnew__container-form-item
                %h5.attendnew__container-form-title 住所（都道府県）
                = u.text_field :address_pref, class: "attendnew__container-form-text", required: :required
              .attendnew__container-form-item
                %h5.attendnew__container-form-title 住所（市区町村）
                = u.text_field :address_details, class: "attendnew__container-form-text", required: :required
              .attendnew__container-form-item
                %h5.attendnew__container-form-title Tel
                = u.text_field :tel, class: "attendnew__container-form-text", required: :required
              .attendnew__container-form-item
                %h5.attendnew__container-form-title メールアドレス
                = current_user.email
      = f.submit "申し込む", class: "attendnew__container-form-btn-submit"
      = link_to "前に戻る", "javascript:void(0)", class: "attendnew__container-form-btn-back"